### PR TITLE
uptime reporting

### PR DESCRIPTION
**Pull request by aervin**
Warning: CORS policy prevent localhost from working

### CODE REVIEW

**Review by feydkin — APPROVED** [review]
Looks good

**Review by undsoft — CHANGES_REQUESTED** [review]
Well, I was only semi joking when I said that we may need to prepare for 99.999% or something similar.
If we are down for 10 minutes, that's 99.99%, and we want to show full number, not just 99% as 99 can be interpreted as being down for hours. 
https://en.wikipedia.org/wiki/High_availability

**Comment by undsoft** [comment]
1. I've disabled CORS in firefox with a plugin. I get "can't access property "statistics", state.uptimeReport is null"
2. Would be good not to show anything about uptime if we have failed to load it.
3. Can we have a link to a 3rd party page, so that people can verify our claims?

**Comment by aervin** [comment]
Sounds good. I think we should have a more detailed card on the stats page for uptime reporting, with extra info and a link as you suggest. But that's better left for another PR.

**Comment by undsoft** [comment]
"ERROR TypeError: can't access property "statistics", state.uptimeReport is null" this time.

**Comment by aervin** [comment]
No such issues with CORS plugin enabled on Chrome and Firefox. Can you try again?

**Pull request merged**
