### PR TITLE
Linter improvements

### PR DESCRIPTION
**Pull request by undsoft**

### CODE REVIEW

**Comment by undsoft** [comment]
@feydkin Can you pull this branch, do `npm i`, then open any of the ts files and add `const x: any = 2;` and try to commit?

**Comment by feydkin** [comment]
`npm i`
```PS C:\Users\jaret\website> nvs
PATH -= C:\Program Files\nodejs
PATH += $env:LOCALAPPDATA\nvs\node\16.4.2\x64
PS C:\Users\jaret\website> npm i

> truepool@0.0.0 prepare
> husky install

husky - Git hooks installed

removed 3 packages, changed 2 packages, and audited 1500 packages in 6s

129 packages are looking for funding
  run `npm fund` for details

6 vulnerabilities (5 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run 'npm audit' for details.
PS C:\Users\jaret\website>
```

`commit`
```> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
.husky/pre-commit: line 4: npm: command not found
husky - pre-commit hook exited with code 127 (error)
```

**Comment by feydkin** [comment]
I don't yet know why but I think it's just a path issue remaining on my end. Running manually seems to produce the expected results.

```PS C:\Users\jaret\website> nvs
PATH -= C:\Program Files\nodejs
PATH += $env:LOCALAPPDATA\nvs\node\14.17.4\x64
PS C:\Users\jaret\website> npm run lint-staged

> truepool@0.0.0 lint-staged C:\Users\jaret\website
> lint-staged

✔ Preparing...
⚠ Running tasks...
  ❯ Running tasks for *.ts
    ✖ eslint --cache --fix [FAILED]
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up...

✖ eslint --cache --fix:

C:\Users\jaret\website\src\app\app-routing.module.ts
  73:7   error  'x' is assigned a value but never used    unused-imports/no-unused-vars
  73:10  error  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

✖ 2 problems (2 errors, 0 warnings)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! truepool@0.0.0 lint-staged: `lint-staged`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the truepool@0.0.0 lint-staged script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jaret\AppData\Roaming\npm-cache\_logs\2021-08-08T17_42_47_554Z-debug.log
PS C:\Users\jaret\website> 
```

**Review by feydkin — APPROVED** [review]
Your changes are good. I fixed the issues on my end. Good to go.

**Comment by aervin** [comment]
this works well here, implicit and explicit `any` is covered. can we add `.eslintcache` to `.gitignore` while we're at it?

**Pull request merged**
