### PR TITLE
Darkmode

### PR DESCRIPTION
**Pull request by feydkin**
#18 - addressing the issues 1 & 2 raised by @undsoft - Please elaborate on issue 3 

> 3 -  When setting name on light theme, it used to be that page background was dark with white rectangle in the middle. Now it's all white.

### CODE REVIEW

**Comment by undsoft** [comment]
Before dark mode, this page also had dark background: 
Снимок экрана 2021-08-11 в 07 23 48

Now, it's just all white. I think it's okay to bring the dark background back for this page in light mode.

**Review by undsoft — APPROVED** [review]
Looks good, I think it's time to deploy to prod.

**Comment by feydkin** [comment]
> 
> 
> Looks good, I think it's time to deploy to prod.

Great, go ahead

**Comment by undsoft** [comment]
Can you make a PR for master? Can’t just deploy develop - there is other stuff in it.

**Pull request merged**
